### ISSUE TITLE
Setup Bug

### ISSUE THREAD

**Issue by mkounkel** [piccolomo/peaky#1]
Hello,

This seems like a fantastic tool, and I'm hoping for my students to use it in the classroom, but I was wondering if it would be possible for you to fix the setup script? When I try to pip install it, I get the error of

> Building wheels for collected packages: peaky
>   Building wheel for peaky (setup.py) ... done
>   Created wheel for peaky: filename=peaky-1.0.41-py3-none-any.whl size=10012 sha256=6987607f40936218e6f892efa674a6a34e11bda98dc8a5f66dcc419a15157f87
>   Stored in directory: /tmp/pip-ephem-wheel-cache-b_h8wvo8/wheels/51/65/51/e997cb9aecdaf15543b435f3a2700a57308aa47ca358dd0d66
> Successfully built peaky
> Installing collected packages: peaky
> Successfully installed peaky-1.0.41
> 
> WARNING: The following packages were previously imported in this runtime:
>   [code]
> You must restart the runtime in order to use newly installed versions.

and then everything just kind of breaks, and it can't import this module, seems like it can't navigate the directory tree. I was able to hack around it by cloning the repo and importing the script itself, but for students it would be nice if it would be possible to streamline it a bit.

Thanks!

**Comment by piccolomo** [comment]
Hi @mkounkel,

I am glad you appreciate the package. 

I am not particularly sure about what that error is and how to solve it. But from a quick online search it seems that the even though the package was installed, the currently running environment won't automatically use the newly installed version. Possible solution:

Restart the Runtime/Environment:

If you're working in an environment like Jupyter Notebook, Google Colab, or another interactive Python environment, you should restart the kernel or runtime. This will reload all the packages, including the newly installed ones.
In Jupyter Notebook, you can do this by going to the menu: Kernel -> Restart Kernel.

After restarting the runtime, you should re-import the peaky package or any other relevant modules. This will ensure that you're using the newly installed version.

By the way, I have updated peaky to version 1.1 from version 1.0, available on both [GitHub](https://github.com/piccolomo/peaky) and [PyPi](https://pypi.org/project/peaky/1.1/).

I hope this help and let me know f you need further assistance.

All the best,
Savino

**Comment by mkounkel** [comment]
It wasn't the issue of restarting the environment, "code" was trying to overwrite some fundamental function within python, which was causing it to break.

But, thank you so much - renaming it fixed it.

**Comment by piccolomo** [comment]
Hi, I suspect in the previous version I overwritten the default function `round()`, which has been renamed in new version to `str_round()`. 

The issue should be solved and hopefully I did not mess the code up.

Thanks for the report. 
Savino
